### ISSUE TITLE
TODO Update list for API V8

### ISSUE THREAD

**Issue by vicky5124** [serenity-rs/serenity#1009]
- [x] (???) Update intents to default to all but privileged; this is necessary as intents are required on V8
- [x] Do not cache Members by default, it can severely slow down the startup speed of the bot if the members and presence intents are not present.
- [x] (#1036) Depend less on cache internally (specially members due to privileged intents being mandatory), make most of the internal methods fall back to http if not present in cache.
- [x] (#1063) Permissions field is now a String.
- [x] (#1043) `game` fields have been replaced with the first element in activities.
- [x] (#1063) Channel Permission Overwirtes `type` field is now serialized as an integer rather than a String.
- [x] (#1043) `embed_enabled` and `embed_channel_id` have been replaced with this: https://discord.com/developers/docs/resources/guild#guild-widget-object
- [x] (Doesn't need fixing) Form error responses now have a format that is better aligned with "regular errors".
- [x] (#1043) Rate limit headers are sending seconds instead of milliseconds. 
- [x] (#1043) The X-RateLimit-Precision header is no longer respected.
- [x] (#1043) Bots no longer get CHANNEL_CREATE for private channels. Remove the private_channel_create event.
- [x] (#1043) Bans `delete-message-days` is replaced with `delete_message_days`
- [x] (#1043) Removed roles, premium_since, and nick from Presence Update gateway event.
- [x] (#991) Inline Replies.
- [x] (#1043) Remove `guild_subscriptions` as it isn't supported anymore due to v6 requiring intents now.
- [x] (#1042) Change the `Vec<GuildId>` to a singular GuildId in `chunk_guilds` related APIs as it only support one guild per request now.
- [x] (#1073) Update `VoiceState` to include `guild_id`, `member`, and `self_video` fields.
- [x] (Fixed Itself) Fix Sequence off warnings on PresenceUpdateEvent (#1082)

NOTE: This list may be non-exhaustive.

**Comment by ikkerens** [comment]
To add, there are two things to uncomment in my pending PR: https://github.com/serenity-rs/serenity/pull/991

**Comment by iirelu** [comment]
I don't know if it's related to this issue but sometime in the last few weeks, the Message::member method no longer works. Just returns None. Do I have to wait until this issue is fixed?

**Comment by ikkerens** [comment]
> I don't know if it's related to this issue but sometime in the last few weeks, the Message::member method no longer works. Just returns None. Do I have to wait until this issue is fixed?

That is related to the new intents rollout. Be sure to enable this checkbox:
![image](https://user-images.githubusercontent.com/1952177/97491090-fa7dc280-1961-11eb-97f4-2030f8729aa1.png)

And request your intents using the ClientBuilder of serenity.

**Comment by james7132** [comment]
Some more things to add to the list that are also relevant to v6:
- [x] Remove `guild_subscriptions` as it isn't supported anymore due to v6 requiring intents now.
- [x] ~~Change the `Vec<GuildId>` to a singular GuildId in `chunk_guilds` related APIs as it only support one guild per request now.~~

**Comment by Erk-** [comment]
@james7132 Your second point "Change the Vec<GuildId> to a singular GuildId..." is also on v6 now so it should probably me moved into its own issue for 0.9

**Comment by FelixMcFelix** [comment]
#1064 should fulfil "Permissions field is now a String".

**Comment by Ceikry** [comment]
> > I don't know if it's related to this issue but sometime in the last few weeks, the Message::member method no longer works. Just returns None. Do I have to wait until this issue is fixed?
> 
> That is related to the new intents rollout. Be sure to enable this checkbox:
> ![image](https://user-images.githubusercontent.com/1952177/97491090-fa7dc280-1961-11eb-97f4-2030f8729aa1.png)
> 
> And request your intents using the ClientBuilder of serenity.

> And request your intents using the ClientBuilder

Is there documentation on this? I was completely failing to understand why the member join listener wasn't firing until I saw this line.

**Comment by Zaitara** [comment]
Serenity now fully supports v8, see above PRs. This can now be closed
