### ISSUE TITLE
Add support for Message Forwarding

### ISSUE THREAD

**Issue by GnomedDev** [serenity-rs/serenity#2995]
https://discord.com/developers/docs/change-log#message-forwarding-rollout
- [x] Add `MessageReference::type` and corresponding enum: #2994
- [x] Add `Message::message_snapshots` field and corresponding `MessageSnapshot` type
- [x] Add builder methods if bots can forward messages.

**Comment by arqunis** [comment]
> Add builder methods if bots can forward messages.

Bots can create forwarded messages by passing
```rust
MessageReference::new(MessageReferenceKind::Forward, <channel-source-of-message-to-forward>)
    .message_id(<id-of-message-to-forward>)
```
to https://serenity-rs.github.io/serenity/current/serenity/builder/struct.CreateMessage.html#method.reference_message.
