### ISSUE TITLE
Road Map for v0.6.0

### ISSUE THREAD

**Issue by Lakelezz** [serenity-rs/serenity#428]
This road map organises features that we consider or want to ship with `v0.6.0`. It's an incomplete collection continuously striving to be updated.
* `Proposed` are features that could qualify for `v0.6.0` but are yet neither confirmed nor implemented.
* `Accepted & WIP` are features that will ship with `v0.6.0` but are still being implemented.
* `Implemented` are features that are ready to ship and merged (or waiting to be) into `v0.6.0`.

Serenity `v0.6.0-rc.0`, `v0.6.0-rc.1`, `v0.6.0-rc.2`, `v0.6.0-rc.2.1`  got released!
`v0.6.0-rc.2.1` fixes a fatal bug in `v0.6.0-rc.2` related to the attribute driven framework.
`v0.6.0-rc.2.1`.

**`v0.6.0` has been released.**

Current road map stage:
- [x] Decided on all features to implement.
- [x] Implemented all features.
- [x] Fully updated Rust-code to latest Rust version.
- [x] Decided on final design for Cache and HTTP related API (see: #470)
- [x] Finish all TODOs.
- [x] Update all examples and make sure they compile.
- [x] Consider all related PRs:
  -  [x] Raw events: #519 
  -  [x] Make `Error` sync: #406 / #532 
  -  [x] Modular event-handler: #424 
- [x] Fix all bugs.
- [x] Update Rust Code.

# Updating Rust Code
- [x] As of [Rust 1.26.0](https://blog.rust-lang.org/2018/05/10/Rust-1.26.html), pattern matching automatically applies dereferencing, thus we can update our `match`s to accept `T` instead of `&T`. This is fixed with #445.
- [x] As of [Rust 1.31.0](https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html) quite a few changes stabilised. These were adopted with #445.
- [x] Future-proofing `enum`s and `struct`s to be exhaustively unmatchable and thus gain changeability of public fields without causing a breaking change. 
- [x] Consider all Clippy-lints, this also includes reconsidering currently allowed lints. This was done in #531.

# Accepted & WIP
- MD Book,
  - **About**: A book about serenity informing users on how to use the library.
  - **Location**: https://github.com/serenity-rs/book

# Implemented
- Support multiple dynamic Prefixes,
  - **About**: Adds the possibility to define multiple prefixes for a specific runtime determined circumstance (e.g. a specific guild).
  - **Breaking**: Changes types on public fields and signature of `dynamic_prefix`, which might be renamed to `dynamic_prefixes` or will coexist.
- **Implementation**: #458 

- Proc-Macro Commands/Framework,
  - **About**: Fundamentally changes how commands are built by using attributes above functions.
  - **Breaking**: Builders to create commands will no longer exist.
  - **How to upgrade**: Port all your commands to attribute-driven commands.
  - **Implementation**: #458 

- Nested Groups,
  - **About**: Allow nesting groups inside groups.
  - **Breaking**: `v0.5.x`'s `CommandGroup` exposes all fields as `pub` and adding a new field would break creation of given type.
  - **Implementation**: #458 

- Support sub-groups in the Help-system,
  - **About**: New command-groups can have sub-groups, which is another group inside a group. This adds support for the help-system to display these in a fancy way.
  - **Breaking**: Can change output-length of help-command and thus may exceed Discord's limit.
  - **Implementation**: #539 

- Switch to `audiopus`,
  - **About**: Switch to `audiopus` to offer Windows' voice-support and update outdated Opus version.
  - **Breaking**: `OpusError` will now yield a different error-enum from `audiopus`.
  - **Implementation**: #522 

- Support Rustls and OpenSSL,
  - **About**: Switch to Rustls by default and offer a feature to depend on OpenSSL instead.
  - **Implementation**: #457 

- Plain-help gets little facelift,
  - **About**: Readability is improved by underlining topic.
  - **Breaking**: Underlining increases characters used and may exceed maximum by Discord.
  - **How to upgrade**: If your help is close to maximum and would exceed, shorten amount of used characters.
  - **Implementation**: #403

- Slow Mode,
  - **About**: Allows checking whether current channel is using a per user ratelimit and to set it.
  - **Breaking**: Both `with_embeds` and `plain` need to change their signature to accept a `HashSet` with related owners.
  - **How to upgrade**: Add field `slow_mode_rate` for manually constructed `GuildChannel`s.
  - **Implementation**: #439

- Fix OpenSSL,
  - **About**: Latest stable OpenSSL version does not build with `serenity`.
  - **Breaking**: `HyperError` has been removed.
  - **How to upgrade**: Use `HttpError` instead.
  - **Implementation**: Switch to `reqwest` with #440 and `tungstenite` with #341.

- Builders borrow themselves via `&mut self`,
  - **About**: Allows to process a builder without chaining them or binding values again.
  - **Implementation**: #443 and #447 

- Use `RwLock` for `ShareMap` instead of `Mutex`,
  - **About**: In some cases reading from the `ShareMap` is required only, however `Mutex` disallows multiple readers.
  - **Breaking**: `lock()` is not implemented on `RwLock`.
  - **How to upgrade**: All `lock()`-calls on the `ShareMap` need to be changed to either `read()` or `write()`.
  - **Implementation**: #453 

- Remove global Cache and HTTP,
  - **About**: In `v0.5.x` both can be freely accessed from everywhere. In `v0.6.x`, these two would be passed around - maybe passed inside `Context`.
  - **Breaking**: E.g. `ChannelId(u64).say(impl Display)` will no longer work, every portion relying on HTTP and Cache as global will break.
  - **Implementation**: #448 and #456 

- Named Checks returning reasoned Errors
  - **About**: `0.5.x`-checks were simply returning a `bool` to express success and failure, the new checks can store a possible name, help-display-options, help-bypass-option, and return `CheckResult` to provide an expressive handling of failures (e.g. to log or inform the user).
  - **Breaking**: The signature of the check function changed.
  - **How to upgrade**: Make checks return `CheckResult` instead of `bool`; they implement `From<bool>` as well if you do not want to use `CheckResult`.
  - **Implementation**: #479 

- Update Help-System
  - **About**: Improve help-system by adding owner-checks, improved checks, ...
  - **Breaking**: Both `with_embeds` and `plain` need to change their signature to accept a `HashSet` with related owners.
  - **Implementation**: #479, #479, #485 

# Bugs to fix before RC:
- [x] Since `tungstenite`-switch, `voice`-features encounter frequent disconnects and instability.
  - Fixed in: #444
- [x] `VoiceState.channel_id` is `None`: #513

# Declined

- Async serenity
  - **Reason**: We decided to await async keywords on `stable` Rust, which won't happen until later this year.

- ETF Gateway Support
  - **About**: Support ETF instead of JSON to transmit data, see issue #61.
  - **Reason**: Not a priority.

- Rework Bucket/Custom Command Rate Limiting,
  - **About**: Instead of having a simple and complex bucket we should simplify this to one bucket and extend the functionality as well to further tune and adjust.
  - **Breaking**: Old buckets will no longer exist.
  - **Reason**: To wrap up `v0.6.0`'s already quite big release, we decided to schedule it for the next fitting release.

**Comment by vityafx** [comment]
Personally, I have made my own stuff for creating extensions for my serenity bot. It allows to dynamically insert or remove extensions (which provide different functionality, commands, and so on) and work within a single bot. It would be nice to provide extensibility in the upstream itself. Though, I guess, this will not land in `0.6` as I think you want to release it quite soon, don't you?

**Comment by Lakelezz** [comment]
It would be great if we can take a look at it, please share example code or link to your implementation on your fork : )

**Comment by vityafx** [comment]
> It would be great if we can take a look at it, please share example code or link to your implementation on your fork : )

Oh, it is not in a fork, it is made on top of serenity's public interface :) And it hasn't been finished yet, I am porting it from my old project (which is private) :)

Currently, there is only a simple "extension" trait and a few impls for it which describe it (name, commands, behavior, and so on) and may be easily plugged in (but statically yet) to a serenity instance.

**Comment by fenhl** [comment]
I would like to propose modularized event handlers (#488) as a feature to be included in 0.6.

**Comment by Lakelezz** [comment]
Thanks for all the suggestions - ranging from this issue to our Discord - we decided that to wrap up `v0.6.0`'s feature scope and will no longer accept new suggestions.
If there occurs to be a small issue that can be fixed easily, then sure, we would be willing to sneak that in, but other than that, all 0.6.0 features are listed in the road map.

**Comment by AregevDev** [comment]
MSVC support for sound feature will be very nice, I can help building the native dependencies

**Comment by Lakelezz** [comment]
> 
> 
> MSVC support for sound feature will be very nice, I can help building the native dependencies

It's already supported on the v0.6.x-branch as shown in the road map under **Implemented** referring to #522.
